config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books, only: [:index, :new, :create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :read_book
    validates :image
  end
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :move_to_index, except: [:index]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    if  @book.save
      redirect_to root_path
    else
      render :new
    end  
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :read_book).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>追加が完了しました。</h3>
    <a class="btn" href="/">書籍一覧へ戻る</a>
  </div>
</div>

app/views/books/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">書籍一覧へ戻る</a>
  </div>
</div>

app/views/books/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @book, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "本のタイトル" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :read_book, placeholder: "どこまで読んだか", rows: "10" %>
      <%= form.submit "追加" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="contents row">
  <% @books.each do |book| %>
    <div class="content_post" style="background-image: url(<%= book.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_book_path(book.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', book_path(book.id), method: :delete %>
          </li>
        </ul>
      </div>
      <p><%= book.title %></p>
      <span class="name">
        <%= book.read_book %>
      </span>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>本を追加する</h3>
    <%= form_with(model: @book, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "本のタイトル" %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :read_book, placeholder: "どこまで読んだか", rows: "10" %>
      <%= form.submit "追加" %>
    <% end %>
  </div>
</div>

app/views/books/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">書籍一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">読んだ本</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "本の追加", new_book_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
      <% end %>

      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        read books
      </p>
    </footer>
  </body>
</html>